# Generated by Django 3.1.5 on 2022-02-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineshopapp', '0002_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_image',
            field=models.ImageField(default='static/images/default male prof.jpg', null=True, upload_to='images/'),
        ),
    ]
